### ISSUE TITLE
question - no issue

### ISSUE THREAD

**Issue by davebneufeld** [steelbreeze/state.js#28]
Hi,
I will be looking at your framework tomorrow. Before I ask any stupid (naive) questions, are there references you might recommend I read first (I checked https://state.software/ - but most links seem under-construction). Thanks for considering my request.
Dave

**Comment by mesmo** [comment]
Hi Dave,

There is full documentation for the API: at http://state.software/docs/; I'd also recommend looking at the source code in the examples and test directories.

For a more general background into UML state machines, see http://www.uml-diagrams.org/state-machine-diagrams.html#behavioral-state-machine (state.js does not support entry point, exit point, fork and join pseudo states or submachine states, but is otherwise complete as per this page).

David.

**Comment by mesmo** [comment]
One more important note to add: state.js provides a separation between a state machine model and state machine instances; it is possible to have multiple state machine instances for a single state machine model.
